Dev
jaureguif/blockchain-voting-system pull request #4
Opened 2018-02-06 16:22 UTC by jaureguif

2018-02-06 17:27 UTC, dan-zx requested changes

2018-02-06 17:27 UTC, dan-zx commented on src/main/java/com/epam/asset/tracking/api/EntityController.java
> +
Is this class still in use?

2018-02-06 17:27 UTC, dan-zx commented on src/main/java/com/epam/asset/tracking/dto/validations/ValidationsUtil.java
> +
Is there a reason for this class to be an interface?

2018-02-06 17:28 UTC, dan-zx commented
We can use later this lib to help us with orika mapper configuarion: [orika-spring-boot-starter](https://github.com/akihyro/orika-spring-boot-starter)

2018-02-09 17:26 UTC, jaureguif commented on src/main/java/com/epam/asset/tracking/api/EntityController.java
> +
For now, yes

2018-02-09 17:27 UTC, merged