Sprint 2 Demo
jaureguif/blockchain-voting-system pull request #5
Opened 2018-02-16 17:30 UTC by jaureguif

2018-02-16 17:38 UTC, dan-zx approved these changes
Looks good to me

2018-02-19 16:39 UTC, dan-zx commented on .checkstyle
> +<?xml version="1.0" encoding="UTF-8"?>
This looks like an autogenerated file

2018-02-19 16:42 UTC, dan-zx requested changes
Except from the file .checkstyle, it looks good to me. 
I couldn't find the setting to suppress the checkstyle logs in the console

2018-02-19 17:17 UTC, closed without merging

2018-02-19 18:02 UTC, dioniciorodriguez reviewed
ok

2018-02-19 18:02 UTC, dioniciorodriguez commented on .checkstyle
> +<?xml version="1.0" encoding="UTF-8"?>
niceee teeeaam!!